### ISSUE TITLE
Drag & Drop files to open

### ISSUE THREAD

**Issue by ColdHeat** [Vector35/binaryninja-python#3]
Dragging files onto different windows/tabs to open them would be a very welcome addition to Binja.

**Comment by psifertex** [comment]
Yeah, that's been on the desired feature list for a while. My workaround in the meantime is to ⌘-o /  ⌃-o and then just drop onto the file picker. It's an extra keystroke, but not too much work.

**Comment by psifertex** [comment]
So I looked into doing this (AKA, cribbed off of @D0ntPanic and the C++ implementation) and it turns out there's a bug in QT 4.8 that blocks us on OS X: https://bugreports.qt.io/browse/QTBUG-40449

Unfortunately, the version of pyside we're using isn't compatible with QT 5.4

I guess we could add OS detection and disable the feature on OS X, but that's kinda annoying. If anyone wants to look into this more, here's a start:

https://gist.github.com/psifertex/a06b260e010c54b623bf

(note that `open_file_name` is unimplemented but should be obvious from `def open` what it should be)

**Comment by ColdHeat** [comment]
How do you feel about requiring PyObjC on OSX? 

Despite the bug you can directly call into Foundation to get the right path. I'm trying to get the right call through ctypes but it's not fun.

**Comment by psifertex** [comment]
Yeah, I looked in to that, but It's a pretty big dependency. `brew install pyobjc` took about 20 minutes to build. If you can do it through ctypes I'd /much/ prefer that.

**Comment by ColdHeat** [comment]
I'll keep working on it although instead of building you can do something like:

``` python
import sys
sys.path.append('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC')
import Foundation
```

**Comment by psifertex** [comment]
Hmm, it's in a default install? That might be doable.

**Comment by psifertex** [comment]
Thanks for pointing out it was already installed, Tested as working on Windows and OS X, if someone can check linux that'd be helpful.

**Comment by ColdHeat** [comment]
Works on Linux :+1:
